In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8287, 4267, 8706, 4634],
 [8287, 4267, 8706, 9275],
 [8287, 8576, 8706, 1473],
 [6087, 2586, 7009, 4263, 618],
 [6087, 2586, 7009, 4263, 6271],
 [3291, 8287, 5391, 8706, 8625],
 [7061, 8069, 343, 4263]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8287 4267 8706 4634]
 [   0    0    0    0 8287 4267 8706 9275]
 [   0    0    0    0 8287 8576 8706 1473]
 [   0    0    0 6087 2586 7009 4263  618]
 [   0    0    0 6087 2586 7009 4263 6271]
 [   0    0    0 3291 8287 5391 8706 8625]
 [   0    0    0    0 7061 8069  343 4263]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 149ms/step


array([[[ 0.04568375,  0.02887613, -0.01454271,  0.02042917,
         -0.04668107,  0.01249164,  0.0459052 , -0.00225139,
         -0.01063351,  0.02909693],
        [ 0.04568375,  0.02887613, -0.01454271,  0.02042917,
         -0.04668107,  0.01249164,  0.0459052 , -0.00225139,
         -0.01063351,  0.02909693],
        [ 0.04568375,  0.02887613, -0.01454271,  0.02042917,
         -0.04668107,  0.01249164,  0.0459052 , -0.00225139,
         -0.01063351,  0.02909693],
        [ 0.04568375,  0.02887613, -0.01454271,  0.02042917,
         -0.04668107,  0.01249164,  0.0459052 , -0.00225139,
         -0.01063351,  0.02909693],
        [ 0.02899598,  0.04275313, -0.03976619, -0.00343116,
         -0.02437464, -0.02070495,  0.00290912, -0.01982698,
         -0.01189931,  0.04552433],
        [-0.03774098, -0.04637748,  0.0277439 , -0.03277866,
         -0.01287649, -0.04974669, -0.03920375, -0.01080624,
          0.04027415, -0.00223704],
        [ 0.04207795,  0.00974878, -0.01144118,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 8287, 4267, 8706, 4634])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[ 0.04568375,  0.02887613, -0.01454271,  0.02042917, -0.04668107,
         0.01249164,  0.0459052 , -0.00225139, -0.01063351,  0.02909693],
       [ 0.04568375,  0.02887613, -0.01454271,  0.02042917, -0.04668107,
         0.01249164,  0.0459052 , -0.00225139, -0.01063351,  0.02909693],
       [ 0.04568375,  0.02887613, -0.01454271,  0.02042917, -0.04668107,
         0.01249164,  0.0459052 , -0.00225139, -0.01063351,  0.02909693],
       [ 0.04568375,  0.02887613, -0.01454271,  0.02042917, -0.04668107,
         0.01249164,  0.0459052 , -0.00225139, -0.01063351,  0.02909693],
       [ 0.02899598,  0.04275313, -0.03976619, -0.00343116, -0.02437464,
        -0.02070495,  0.00290912, -0.01982698, -0.01189931,  0.04552433],
       [-0.03774098, -0.04637748,  0.0277439 , -0.03277866, -0.01287649,
        -0.04974669, -0.03920375, -0.01080624,  0.04027415, -0.00223704],
       [ 0.04207795,  0.00974878, -0.01144118,  0.03530017,  0.02336827,
         0.00438665,  0.01361923, -0.00079767